#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/sbin/niseva-agent

start_service() {
	local enabled
	config_load niseva
	config_get_bool enabled general enabled 1

	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	killall -SIGTERM niseva-agent
}

service_triggers() {
	procd_add_reload_trigger "niseva"
}
