import { type ChangeEvent, useEffect, useState } from "react";
import { Check, FileUp, RefreshCw, Router, Trash2, X } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Row = Record<string, any>;
type Entry = { name: string; serial_number: string; lan_mac: string; tags: string[] };
const blank = (): Entry => ({ name: "", serial_number: "", lan_mac: "", tags: [] });
const inputClass = "font-mono text-[11px]";

async function request(path: string, method = "GET", value?: unknown, csv = false) {
  const response = await fetch(`/api/v1/${path}`, { method, credentials: "same-origin", headers: { "Content-Type": csv ? "text/csv" : "application/json" }, body: value === undefined ? undefined : csv ? String(value) : JSON.stringify(value) });
  if (response.status === 204) return null;
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || "Request failed");
  return body;
}

export default function Onboarding({ user }: { user: Row }) {
  const [org, setOrg] = useState(user.organization_id || "");
  const [orgs, setOrgs] = useState<Row[]>([]);
  const [rows, setRows] = useState<Entry[]>([blank()]);
  const [pending, setPending] = useState<Row[]>([]);
  const [registrations, setRegistrations] = useState<Row[]>([]);
  const [tags, setTags] = useState<Row[]>([]);
  const [preview, setPreview] = useState<Row[]>([]);
  const [results, setResults] = useState<Row[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<Row | null>(null);
  const [cancelTarget, setCancelTarget] = useState<Row | null>(null);
  const [editName, setEditName] = useState("");
  const [editTags, setEditTags] = useState<string[]>([]);

  const refresh = async () => { const [nextPending, nextRegistrations, nextTags] = await Promise.all([request("pending-devices"), request("registrations"), request("tags")]); setPending(nextPending || []); setRegistrations(nextRegistrations || []); setTags(nextTags || []); };
  useEffect(() => { refresh().catch((err) => setError(String(err))); if (user.role === "SUPER_ADMIN") request("organizations").then(setOrgs).catch((err) => setError(String(err))); const timer = setInterval(() => refresh().catch((err) => setError(String(err))), 15000); return () => clearInterval(timer); }, []);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); } catch (err) { setError(String(err)); } finally { setBusy(false); } };
  const submit = (entries: Entry[]) => run(async () => { const response = await request("registrations", "POST", { organization_id: org, rows: entries }); setResults(response || []); setRows(entries.filter((_, index) => !response[index]?.success)); setPreview([]); await refresh(); });
  const options = tags.filter((tag) => tag.organization_id === org).map((tag) => tag.name);
  const startEdit = (row: Row, claim: boolean) => { setEditing({ ...row, claim }); setEditName(row.name || ""); setEditTags(row.tags || []); };
  const updateEntry = (index: number, key: keyof Entry, value: string | string[]) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
  const cancelRegistration = () => { if (!cancelTarget) return; const target = cancelTarget; return run(async () => { await request(`registrations/${target.id}`, "DELETE"); setCancelTarget(null); await refresh(); }); };
  const saveEdit = () => { if (!editing) return; const target = editing; return run(async () => { await request(target.claim ? `pending-devices/${target.id}/claim` : `registrations/${target.id}`, target.claim ? "POST" : "PATCH", { name: editName, tags: editTags }); setEditing(null); await refresh(); }); };

  return <div className="mx-auto flex max-w-[1200px] flex-col gap-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-display text-[20px] font-semibold">Onboarding</h1><p className="mt-1 text-[13px] text-muted-foreground">Register device identities or claim routers associated with an enrollment token.</p></div><Button variant="outline" size="sm" onClick={() => void run(refresh)} disabled={busy}><RefreshCw className={busy ? "size-3.5 animate-spin" : "size-3.5"} />Refresh</Button></div>{error && <div role="alert" className="flex items-start justify-between gap-3 rounded-lg border border-down-border bg-down-bg px-3.5 py-3 text-[12px] text-down"><span>{error}</span><button type="button" onClick={() => setError("")} className="font-medium underline underline-offset-2">Dismiss</button></div>}{user.role === "SUPER_ADMIN" && <div className="max-w-[320px]"><label className="mb-1.5 block text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Customer</label><select value={org} onChange={(event) => { setOrg(event.target.value); setPreview([]); setResults([]); }} className="h-9 w-full rounded-md border border-input bg-card px-3 text-[12px] outline-none focus:border-ring focus:ring-2 focus:ring-ring/25"><option value="">Select customer</option>{orgs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>}
    <Card><CardHeader className="border-b border-border"><CardTitle>Device onboarding</CardTitle><CardDescription>Serial number and LAN MAC are used to match the router during its first check-in.</CardDescription></CardHeader><CardContent className="p-4"><Tabs defaultValue="manual"><TabsList><TabsTrigger value="manual">Manual</TabsTrigger><TabsTrigger value="csv">From file</TabsTrigger><TabsTrigger value="pending">Available to claim <span className="font-mono text-[10.5px] opacity-70">{pending.length}</span></TabsTrigger><TabsTrigger value="registrations">Registration requests <span className="font-mono text-[10.5px] opacity-70">{registrations.length}</span></TabsTrigger></TabsList>
      <TabsContent value="manual" className="mt-4"><div className="hidden grid-cols-[1fr_1fr_1fr_1fr_32px] gap-3 border-b border-border pb-2 text-[10.5px] font-semibold uppercase tracking-wide text-muted-foreground lg:grid"><span>Name</span><span>Serial number</span><span>LAN MAC</span><span>Tags</span><span /></div><div className="divide-y divide-border">{rows.map((row, index) => <div key={index} className="grid gap-2.5 py-3 lg:grid-cols-[1fr_1fr_1fr_1fr_32px] lg:items-center lg:gap-3"><Input aria-label={`Name ${index + 1}`} placeholder="Name (optional)" value={row.name} maxLength={128} onChange={(event) => updateEntry(index, "name", event.target.value)} /><Input aria-label={`Serial ${index + 1}`} placeholder="Serial number" maxLength={63} value={row.serial_number} className={inputClass} onChange={(event) => updateEntry(index, "serial_number", event.target.value)} /><Input aria-label={`LAN MAC ${index + 1}`} placeholder="AA:BB:CC:DD:EE:FF" maxLength={17} value={row.lan_mac} className={inputClass} onChange={(event) => updateEntry(index, "lan_mac", event.target.value)} /><Input aria-label={`Tags ${index + 1}`} list="onboarding-tags" placeholder="tag-a, tag-b" value={row.tags.join(", ")} onChange={(event) => updateEntry(index, "tags", event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean))} /><Button variant="ghost" size="icon" aria-label={`Remove row ${index + 1}`} onClick={() => setRows((current) => current.length === 1 ? [blank()] : current.filter((_, rowIndex) => rowIndex !== index))} disabled={busy}><Trash2 className="size-4 text-destructive" /></Button></div>)}</div><datalist id="onboarding-tags">{options.map((option) => <option key={option} value={option} />)}</datalist><div className="mt-3 flex flex-wrap gap-2 border-t border-border pt-4"><Button variant="outline" onClick={() => setRows((current) => [...current, blank()])} disabled={rows.length >= 500 || busy}>Add row</Button><Button onClick={() => submit(rows)} disabled={!org || !rows.length || busy}>Register devices</Button></div></TabsContent>
      <TabsContent value="csv" className="mt-4"><div className="space-y-4"><a download="rms-devices.csv" href={`data:text/csv;charset=utf-8,${encodeURIComponent("name,serial_number,lan_mac,tags\n")}`}><Button variant="outline" asChild><span><FileUp className="size-4" />Download CSV template</span></Button></a><p className="text-xs text-muted-foreground">Maximum 500 rows / 1 MiB. Separate tags with semicolons. Preview first, then confirm valid rows.</p><label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border bg-secondary/35 px-4 py-8 text-center hover:border-primary/50"><FileUp className="size-6 text-primary" /><span className="text-[13px] font-medium">Choose a CSV file</span><input aria-label="Device CSV" type="file" accept=".csv,text/csv" className="sr-only" disabled={!org || busy} onChange={(event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; setPreview([]); if (file) void run(async () => { if (file.size > 1048576) throw new Error("Maximum file size is 1 MiB"); setPreview(await request(`registrations/preview?organization_id=${encodeURIComponent(org)}`, "POST", await file.text(), true)); }); event.target.value = ""; }} /></label>{preview.length > 0 && <><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[13px] font-semibold">Validation preview <span className="font-mono text-xs text-muted-foreground">({preview.filter((item) => item.valid).length} valid / {preview.length} total)</span></span><Button onClick={() => submit(preview.filter((item) => item.valid).map((item) => item.data))} disabled={!preview.some((item) => item.valid) || busy}>Confirm valid rows</Button></div><div className="overflow-hidden rounded-lg border border-border"><Table><TableHeader><TableRow><TableHead>Row</TableHead><TableHead>Serial</TableHead><TableHead>LAN MAC</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{preview.map((item) => <TableRow key={item.row}><TableCell className="font-mono text-[11px]">{item.row}</TableCell><TableCell className="font-mono text-[11px]">{item.data?.serial_number}</TableCell><TableCell className="font-mono text-[11px]">{item.data?.lan_mac}</TableCell><TableCell><Badge variant={item.valid ? "ok" : "down"}>{item.valid ? <><Check className="size-3" />Valid</> : item.error || "Invalid"}</Badge></TableCell></TableRow>)}</TableBody></Table></div></>}</div></TabsContent>
      <TabsContent value="pending" className="mt-4"><Table><TableHeader><TableRow><TableHead>Serial number</TableHead><TableHead>LAN MAC</TableHead><TableHead>Model</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{pending.filter((item) => !org || item.organization_id === org).map((item) => <TableRow key={item.id}><TableCell className="font-mono text-[11px] font-semibold">{item.serial_number}</TableCell><TableCell className="font-mono text-[11px]">{item.lan_mac}</TableCell><TableCell>{item.model || "Niseva router"}</TableCell><TableCell className="text-right"><Button size="sm" onClick={() => startEdit(item, true)}>Claim</Button></TableCell></TableRow>)}</TableBody></Table></TabsContent>
      <TabsContent value="registrations" className="mt-4"><Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Identity</TableHead><TableHead>Tags</TableHead><TableHead>State</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{registrations.filter((item) => !org || item.organization_id === org).map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.name || "Unnamed device"}</TableCell><TableCell><span className="font-mono text-[11px]">{item.serial_number}</span><span className="mt-1 block font-mono text-[10.5px] text-muted-foreground">{item.lan_mac}</span></TableCell><TableCell><div className="flex flex-wrap gap-1">{item.tags?.map((tag: string) => <Badge key={tag} variant="secondary" className="font-normal">{tag}</Badge>)}</div></TableCell><TableCell><Badge variant={item.status === "awaiting_device" ? "warn" : item.status === "claimed" ? "ok" : "neutral"}>{item.status === "awaiting_device" ? "Awaiting device" : item.status}</Badge></TableCell><TableCell className="text-right">{item.status === "awaiting_device" && <div className="flex justify-end gap-1.5"><Button variant="outline" size="sm" onClick={() => startEdit(item, false)}>Edit</Button><Button variant="outline" size="sm" className="text-destructive hover:text-destructive" onClick={() => setCancelTarget(item)}>Cancel</Button></div>}</TableCell></TableRow>)}</TableBody></Table></TabsContent>
    </Tabs></CardContent></Card>
    {!!results.length && <Card><CardHeader><CardTitle>Submission results</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Submitted row</TableHead><TableHead>Result</TableHead></TableRow></TableHeader><TableBody>{results.map((item, index) => <TableRow key={index}><TableCell className="font-mono text-[11px]">{item.row ?? index + 1}</TableCell><TableCell><Badge variant={item.success ? "ok" : "down"}>{item.success ? "Registered" : item.error}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
    <Dialog open={!!editing} onOpenChange={(open) => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>{editing?.claim ? "Claim router" : "Edit registration"}</DialogTitle><DialogDescription>Set the friendly name and customer tags for this device.</DialogDescription></DialogHeader><div className="space-y-4"><Input aria-label="Device name" placeholder="Name (optional)" value={editName} onChange={(event) => setEditName(event.target.value)} /><Input aria-label="Device tags" list="edit-tags" placeholder="Comma-separated tags" value={editTags.join(", ")} onChange={(event) => setEditTags(event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean))} /><datalist id="edit-tags">{tags.filter((tag) => tag.organization_id === editing?.organization_id).map((tag) => <option key={tag.name} value={tag.name} />)}</datalist></div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)} disabled={busy}>Cancel</Button><Button onClick={saveEdit} disabled={busy}>{busy ? "Saving…" : editing?.claim ? "Claim router" : "Save changes"}</Button></DialogFooter></DialogContent></Dialog>
    <ConfirmDialog open={!!cancelTarget} onOpenChange={(open) => !open && setCancelTarget(null)} title="Cancel this registration?" description={cancelTarget ? `Pre-registration for router ${cancelTarget.serial_number} will be removed.` : "This pre-registration will be removed."} confirmLabel="Cancel registration" onConfirm={cancelRegistration} />
  </div>;
}
