import { Terminal } from "xterm";
import "xterm/css/xterm.css";
const terminal = new Terminal({ cols: 100, rows: 30, cursorBlink: true });
terminal.open(document.getElementById("terminal")!);
const socket = new WebSocket(`wss://${location.host}/ws`);
socket.binaryType = "arraybuffer";
socket.onopen = () => terminal.focus();
socket.onmessage = event => terminal.write(typeof event.data === "string" ? event.data : new Uint8Array(event.data));
socket.onclose = () => terminal.write("\r\n[Session closed]\r\n");
socket.onerror = () => terminal.write("\r\n[Connection failed]\r\n");
terminal.onData(data => { if (socket.readyState === WebSocket.OPEN) socket.send(data); });
window.addEventListener("beforeunload", () => socket.close());
