CREATE TABLE organizations (id text PRIMARY KEY, name text NOT NULL);
CREATE TABLE users (id text PRIMARY KEY, organization_id text REFERENCES organizations, email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('SUPER_ADMIN','ORG_ADMIN','OPERATOR','VIEWER')), disabled boolean NOT NULL DEFAULT false);
CREATE TABLE enrollment_tokens (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations, name text NOT NULL, token_hash text UNIQUE NOT NULL, expires_at timestamptz, max_uses integer CHECK(max_uses > 0), used_count integer NOT NULL DEFAULT 0, revoked boolean NOT NULL DEFAULT false);
CREATE TABLE devices (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations, serial_number text UNIQUE NOT NULL, model text NOT NULL, firmware_version text NOT NULL, public_key bytea NOT NULL, revoked boolean NOT NULL DEFAULT false, last_seen timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX devices_tenant ON devices(organization_id,id);
CREATE TABLE recovery_challenges (id text PRIMARY KEY, device_id text NOT NULL REFERENCES devices, message text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE profiles (id text NOT NULL, version integer NOT NULL CHECK(version > 0), name text NOT NULL, definition jsonb NOT NULL, PRIMARY KEY(id,version));
CREATE TABLE assignments (device_id text NOT NULL REFERENCES devices, profile_id text NOT NULL, version integer NOT NULL, active boolean NOT NULL DEFAULT true, PRIMARY KEY(device_id,profile_id,version), FOREIGN KEY(profile_id,version) REFERENCES profiles(id,version));
CREATE TABLE snapshot_cursors (device_id text NOT NULL REFERENCES devices, source_id text NOT NULL, boot_id text NOT NULL, sequence bigint NOT NULL, received_at timestamptz NOT NULL, PRIMARY KEY(device_id,source_id,boot_id));
CREATE TABLE current_snapshots (device_id text NOT NULL REFERENCES devices, source_id text NOT NULL, profile_id text NOT NULL, profile_version integer NOT NULL, boot_id text NOT NULL, sequence bigint NOT NULL, observed_at timestamptz NOT NULL, received_at timestamptz NOT NULL, status text NOT NULL, error text NOT NULL, dropped bigint NOT NULL, data jsonb NOT NULL, fields jsonb NOT NULL, PRIMARY KEY(device_id,source_id));
CREATE INDEX current_fields ON current_snapshots USING gin(fields jsonb_path_ops);
CREATE TABLE snapshot_history (device_id text NOT NULL, source_id text NOT NULL, profile_id text NOT NULL, profile_version integer NOT NULL, observed_at timestamptz NOT NULL, received_at timestamptz NOT NULL, status text NOT NULL, data jsonb NOT NULL, fields jsonb NOT NULL) PARTITION BY RANGE(received_at);
CREATE INDEX history_device ON snapshot_history(device_id,source_id,observed_at);
CREATE TABLE hourly_summaries (device_id text NOT NULL, source_id text NOT NULL, hour timestamptz NOT NULL, fields jsonb NOT NULL, PRIMARY KEY(device_id,source_id,hour));
CREATE TABLE rollup_progress (id integer PRIMARY KEY CHECK(id=1), through timestamptz NOT NULL);
CREATE TABLE dirty_hours (device_id text NOT NULL, source_id text NOT NULL, hour timestamptz NOT NULL, PRIMARY KEY(device_id,source_id,hour));
CREATE TABLE sessions (id text PRIMARY KEY, device_id text NOT NULL REFERENCES devices, user_id text NOT NULL REFERENCES users, protocol text NOT NULL CHECK(protocol IN ('HTTP_LUCI','TERMINAL_SSH')), ticket_hash text NOT NULL, expires_at timestamptz NOT NULL, closed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX one_session_per_device ON sessions(device_id) WHERE closed_at IS NULL;
ALTER TABLE sessions ADD COLUMN browser_hash text NOT NULL DEFAULT '';
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, organization_id text REFERENCES organizations, user_id text, action text NOT NULL, resource_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE collector_bundles (id text PRIMARY KEY, version integer NOT NULL, manifest jsonb NOT NULL, script text NOT NULL, signature text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
